// Importing mongoose
const mongoose = require("mongoose");

// Defining the dispenser schema
const dispenserSchema = new mongoose.Schema({
  // The status of the dispenser, either "open" or "closed"
  // Default is "closed"
  status: {
    type: String,
    default: "closed",
    enum: ["open", "closed"],
  },
  // The flow volume of the dispenser
  // This is a required field
  flow_volume: {
    type: Number,
    required: true,
  },
  // The time when the dispenser was opened
  openTime: {
    type: Date,
  },
  // The total amount of beer served by the dispenser
  // Initialized to 0
  totalServed: {
    type: Number,
    default: 0,
  },
  // The total revenue generated by the dispenser
  // Initialized to 0
  totalRevenue: {
    type: Number,
    default: 0,
  },
  // The price per liter of beer
  // Default is 5
  pricePerLiter: {
    type: Number,
    default: 5,
  },
  // The total number of uses of the dispenser
  // Initialized to 0
  totalUses: {
    type: Number,
    default: 0,
  },
  // The total time the dispenser has been open
  // Time is measured in seconds and is initialized to 0
  totalOpenTime: {
    type: Number, // time in seconds
    default: 0,
  },
  // The total volume of beer that the dispenser can hold
  // This is a required field
  totalVolume: {
    type: Number,
    required: true,
  },
  // The current volume of beer in the dispenser
  // Initialized to totalVolume
  currentVolume: {
    type: Number,
    default: function () {
      return this.totalVolume;
    }, // initialize to totalVolume
  },
});

// Creating the Dispenser model from the dispenser schema
const Dispenser = mongoose.model("Dispenser", dispenserSchema);

// Exporting the Dispenser model
module.exports = Dispenser;
